# Generated by Django 3.2.12 on 2022-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_pricelookupevent_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='one_off_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
