# Generated by Django 3.2.12 on 2022-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_company_one_off_scrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_granular_scraping',
            field=models.BooleanField(default=False),
        ),
    ]
